name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate Snake
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: Chaplot05
          outputs: |
            dist/github-contribution-grid-snake.svg?color_snake=#C8C3FF&color_dots=#ebedf0,#9be9a8,#40c463,#30a14e,#216e39
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark&color_snake=#FF2D55

      - name: Deploy to output branch
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          branch: output
